version: '3.8'

services:
  mysql:
    image: glakowski/bazy_obraz:latest
    container_name: bazy_kontner
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pbazy123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

      
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: bazy123
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
